# Generated by Django 2.2.1 on 2019-06-14 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(verbose_name='contacted by')),
            ],
        ),
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('hash', models.TextField(default='pbkdf2_sha256$150000$22l3vO9xrXlt$LmtcKGOOVynr67ZzsQBo2kYg8B+/jkiz3GN3qFAHyHA=')),
            ],
        ),
        migrations.CreateModel(
            name='LoginRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='login date')),
                ('mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confession_site.Moderator')),
            ],
        ),
        migrations.CreateModel(
            name='Confession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confession_text', models.TextField()),
                ('confess_date', models.DateTimeField(verbose_name='date published')),
                ('confession_published', models.TextField(default='Unpublished')),
                ('confession_edited', models.TextField(default='No')),
                ('confession_edited_date', models.DateTimeField(verbose_name='date edited')),
                ('confession_edited_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='confession_site.Moderator')),
            ],
        ),
    ]
