# Generated by Django 2.2.1 on 2019-06-15 02:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('confession_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='confession',
            name='confession_picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='pictures'),
        ),
        migrations.AlterField(
            model_name='contactrecord',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 15, 2, 33, 18, 633794, tzinfo=utc), verbose_name='contacted by'),
        ),
        migrations.AlterField(
            model_name='moderator',
            name='hash',
            field=models.TextField(default='pbkdf2_sha256$150000$Wrrmwu1ssJ23$FjKkVYr5umXN2TwnsYGsLxkBuiEmFAunU2yKQ/wu2pE='),
        ),
    ]
