# Generated by Django 2.2.1 on 2019-06-15 11:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('confession_site', '0002_auto_20190615_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confession',
            name='confession_picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='pictures/'),
        ),
        migrations.AlterField(
            model_name='contactrecord',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 15, 11, 8, 29, 866196, tzinfo=utc), verbose_name='contacted by'),
        ),
        migrations.AlterField(
            model_name='moderator',
            name='hash',
            field=models.TextField(default='pbkdf2_sha256$150000$wEg9X3B8FfHE$3bLH30PlJX3Cht9jBTL1gdreFkrJvFM4BUI6MSIikSE='),
        ),
    ]
